language: c++
sudo: required

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3

install: ./install-dependencies.sh

script:
    - eval `opam config env` && make unittests 
    - eval `opam config env` && make doc
    - eval `opam config env` && make default
    - make clean

env:
    - OCAML_VERSION=4.04.0

notifications:
    email:
        - laurent.prosperi@ens-cachan.fr
        - rebeccazr@hotmail.fr
